<?php
function Conectarse()
{
    if (!($link=mysql_connect("localhost","root","root")))
   //if (!($link=mysql_connect("mysql.hostinger.mx","u870355355_rb","2Zt8&(36c#^{<=W")))
   {
      echo "Error conectando a la base de datos.";
      exit();	  
   }
   if (!mysql_select_db("imagenes",$link))
   {
      echo "Error seleccionando la base de datos.";
      exit();
   }
   return $link;
}
$link=Conectarse();
?>